CREATE TABLE "facilities" (
	"ft_idx" bigint PRIMARY KEY NOT NULL,
	"ar_cd_name" text DEFAULT '' NOT NULL,
	"ft_title" text DEFAULT '' NOT NULL,
	"bk_cd_name" text DEFAULT '' NOT NULL,
	"ft_post" text DEFAULT '' NOT NULL,
	"ft_addr" text DEFAULT '' NOT NULL,
	"ft_addr_detail" text DEFAULT '' NOT NULL,
	"ft_size" text DEFAULT '' NOT NULL,
	"ft_org" text DEFAULT '' NOT NULL,
	"ft_phone" text DEFAULT '' NOT NULL,
	"ft_wd_time" text DEFAULT '' NOT NULL,
	"ft_we_time" text DEFAULT '' NOT NULL,
	"ft_info_time" text DEFAULT '' NOT NULL,
	"rt_cd_name" text DEFAULT '' NOT NULL,
	"ft_money" text DEFAULT '' NOT NULL,
	"ft_park" text DEFAULT '' NOT NULL,
	"ft_homepage" text DEFAULT '' NOT NULL,
	"ft_kind_name" text DEFAULT '' NOT NULL,
	"ft_operation_name" text DEFAULT '' NOT NULL,
	"ft_si" text DEFAULT '' NOT NULL,
	"ft_bigo" text DEFAULT '' NOT NULL,
	"images" text[] DEFAULT '{}' NOT NULL
);
