name: Manual Build and Execute

on:
  workflow_dispatch: 

jobs:
  build-and-execute:
    runs-on: ubuntu-latest
    environment: secrets
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_KEY: ${{ secrets. API_KEY }}
      OPEN_API_URL: ${{ secrets.OPEN_API_URL }}
      SPORTS_URL: ${{ secrets.SPORTS_URL }}
      SPORTS_URL_PATH: ${{ secrets.SPORTS_URL_PATH }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Execute
        if: success()
        run: pnpm execute 